name: youxinbao
description: 优信保

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  event_bus: ^1.0.1
  cached_network_image: ^0.8.0
  flutter_screenutil: ^0.4.2
  font_awesome_flutter: ^8.4.0
  permission_handler: 2.1.3
  image_picker: ^0.6.0+2
  city_pickers: ^0.1.16
  date_range_picker: ^1.0.5
  charts_flutter: ^0.6.0
  shared_preferences: ^0.5.1+2
  common_utils: ^1.1.1
  rxdart: ^0.21.0
  flukit: ^1.0.0
  dio: ^1.0.13
  carousel_slider: ^1.3.0
  flutter_swiper: ^1.1.6
  toast: ^0.1.4
  xs_progress_hud: ^1.0.2
  rflutter_alert: ^1.0.2
  flare_flutter: ^1.5.4
  flutter_easyrefresh: ^1.2.7
  path: ^1.6.2
  webview_flutter: ^0.3.4
  flutter_inappbrowser: ^1.2.1
  multi_image_picker: ^4.3.3
  jpush_flutter: ^0.0.11      
  fake_alipay: ^0.2.0
  fake_wechat: ^0.3.1
  numberpicker: ^1.0.0
  date_format: ^1.0.6
  # flutter_luban: ^0.1.7+1
  path_provider: ^0.5.0
  flutter_image_compress: ^0.6.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/user/
    - assets/images/splash/
    - assets/animations/